### ISSUE TITLE
Missing context menu on folders in explorer to set subdirectory

### ISSUE THREAD

**Issue by StJohn3D** [maty21/mocha-sidebar#115]
### Description
Missing context menu on folders in explorer to set subdirectory

#### Steps to Reproduce
1. Open VSC
2. Install mocha-sidebar
3. R-Click any folder

#### Expected Results
Context menu option to set mocha sidebar subdirectory

#### Actual Results
No Mocha Sidebar related context menu options at all 

#### Settings file

none, just rolling with the default installation

### Versions

- VScode: v1.24.1
- Mocha SideBar: v0.20.4
- Node Version: v8.9.4

### OS version

- [ ] Linux 
- [ ] Mac
- [x] Windows 10 Pro v1803

#### Example for reproducing
![Image of context menu](https://files.gitter.im/mocha-sidebar/Questions/hJoE/image.png)

**Comment by yehiyam** [comment]
hi @StJohn3D 
I've created a new version (0.20.7). Could you please try it and let us know
https://files.fm/u/qsq54k9k
We want to wait for your input before publishing

**Comment by StJohn3D** [comment]
Sorry, for just now responding. I need to be better about checking my email. Ok so I uninstalled the public version and installed from that .vsix file and the context menu option is now present. So I can r-click folders and click set sub-directory now. I don't know if it actually works though. The explorer looks like it's stuck searching. There's this waiting icon and blue progress line that never go away.
![vsc-mocha-sidebar-0.20.7-test](https://files.gitter.im/mocha-sidebar/Questions/YfTz/vs-mocha-sidebar-test.png)

Also it's not finding any of my tests. I might need to set some config options though. I pointed it to a directory with a folder in it called tests, and a test file in there called *.spec.js

I tried setting these config values. The sub-directory value was set using the r-click context menu
```js
{
  // Mocha: Subdirectory in the Workspace where run mocha from
  "mocha.subdirectory": "..\\..\\..\\..\\..\\c:\\Users\\stjoh\\Projects\\Navex\\empapp-curator\\client",
  // Mocha: Glob to search for test files
  "mocha.files.glob": "./src/tests/**/*.spec.js",
}
```
The fully qualified path to the test file is `C:\Users\stjoh\Projects\Navex\empapp-curator\client\src\tests\pages\intake-password\intake-password.spec.js`

Something I'm missing in my work-space settings that I have when I call mocha from the cl are these options.
```
./src/tests/helpers/setup.js
./src/tests/**/*.spec.js
-r chai/register-should
-r chai/register-expect
```
I'm not sure how to translate those last two options into the work-space settings. The documentation for mocha-side-bar just points me to a source mocha js file which isn't super intuitive.

The second option from the top I believe is handled by `mocha.files.glob` in my work-space settings. But where should I put the setup file? Would it go in `mocha.requires`?

**Comment by maty21** [comment]
Does this issue solved in 0.2.11 ?

**Comment by StJohn3D** [comment]
@maty21 The original issue, (Right Click context menu option missing) has been resolved in 0.20.11
It properly sets the value in work-space settings. It's still not finding my tests so either I'm not understanding the config options or there's a separate issue. The endless searching described in my last comment is also still happening.

I'll go ahead and close this issue since the original problem has been solved. Just know that it is still unusable for me as it just gets stuck in an endless search for tests and never finds them despite my best efforts to get the work-space configuration right.

Also something to think about. My team keeps our work-space settings under source control so we can share settings. So switching the sub-directory from server to client isn't something we'd want to commit and it'd get a annoying to have to constantly discard that change in git. It'd be nice if we had the option to put some or all of the options in our user-settings instead. As is I don't think we can use it since we don't want to fight with that sub-directory value constantly changing in our work-space settings.

**Comment by maty21** [comment]
hi,

do you have code, configuration to share in order to reproduce it

**Comment by maty21** [comment]
about workspace it's on our roadmap

**Comment by StJohn3D** [comment]
@maty21 
Sorry, I've cleared everything out. But I can describe our stack. We used create-react-app to jump start things. So the file structure is as follows
```
root./
├── README.md
├── node_modules
├── package.json
├── .gitignore
├── client/
     ├── node_modules
     ├── package.json
     ├── app/
     │   └── all of our .ts and .tsx files
     │   ├── tests/
     │   │   └── all of our .ts and .tsx test files
     ├── src/
     │   └── all of our compiled .js files
     │   ├── tests/
     │   │   └── all of our compiled .js test files
├── server/
     ├── node_modules
     ├── package.json
     ├── app/
     │   └── all of our .ts files
     │   ├── tests/
     │   │   └── all of our .ts test files
     ├── src/
     │   └── all of our compiled .js files
     │   ├── tests/
     │   │   └── all of our compiled .js test files
```

We have work-space settings that are tracked in git and shared across the team. Mostly ts-lint options.

So there's the basic setup. If there was a way to easily point Mocha-sidebar at our `src/tests/**/*.spec.js` files in either client/ or server/ and have it actually find them would be great. One more thing with us, idk how this happened but our server output actually includes the app folder for some reason so it would be `server/src/app/tests/**/*.spec.js`

Anyway, last I checked switching was working, it just wasn't finding any test files. But since it'd be a huge pain to constantly ignore the workspace-settings change in git, I've uninstalled it for the time-being.
